# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=200)),
                ('pos_degree', models.CharField(max_length=200)),
            ],
        ),
    ]
