# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PosDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.DateField(verbose_name='Project initialization')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='pos_degree',
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('institution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='condet.Institution')),
            ],
            bases=('condet.institution',),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condet.Institution'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condet.Researcher'),
        ),
        migrations.AddField(
            model_name='project',
            name='institution',
            field=models.ManyToManyField(to='condet.Institution'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(to='condet.ProjectMember'),
        ),
        migrations.AddField(
            model_name='courseteacher',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condet.Position'),
        ),
        migrations.AddField(
            model_name='courseteacher',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condet.Researcher'),
        ),
        migrations.AddField(
            model_name='course',
            name='researchers',
            field=models.ManyToManyField(to='condet.CourseTeacher'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='degree',
            field=models.ManyToManyField(to='condet.Degree'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='pos_degree',
            field=models.ManyToManyField(to='condet.PosDegree'),
        ),
        migrations.AddField(
            model_name='university',
            name='courses',
            field=models.ManyToManyField(to='condet.Course'),
        ),
    ]
