# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condet', '0002_auto_20170629_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researcher',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='researcher',
            name='last_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
