# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condet', '0003_auto_20170629_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseteacher',
            name='position_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseteacher',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
