# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condet', '0004_auto_20170629_2045'),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name='university',
#            name='courses',
#        ),
#        migrations.RemoveField(
#            model_name='university',
#            name='institution_ptr',
#        ),
#        migrations.AddField(
#            model_name='course',
#            name='university',
#            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='condet.Institution'),
#            preserve_default=False,
#        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
