# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condet', '0005_auto_20170630_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('institution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='condet.Institution')),
            ],
            bases=('condet.institution',),
        ),
#        migrations.RemoveField(
#            model_name='course',
#            name='university',
#        ),
        migrations.AddField(
            model_name='university',
            name='courses',
            field=models.ManyToManyField(to='condet.Course'),
        ),
    ]
