# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condet', '0006_auto_20170630_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condet.Position')),
                ('position_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condet.PositionType')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condet.Researcher')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='courseteacher',
            name='position',
        ),
        migrations.RemoveField(
            model_name='courseteacher',
            name='position_type',
        ),
        migrations.AddField(
            model_name='courseteacher',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condet.ProfessorRole'),
        ),
        migrations.AddField(
            model_name='university',
            name='professors',
            field=models.ManyToManyField(to='condet.Professor'),
        ),
    ]
