# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condet', '0007_auto_20170918_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='professors',
        ),
        migrations.AddField(
            model_name='professor',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='condet.University'),
            preserve_default=False,
        ),
    ]
