# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 14:58
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('condet', '0008_auto_20170920_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='geom',
            field=djgeojson.fields.PointField(blank=True, null=True),
        ),
    ]
